version: '2'
services:
  demo:
    build: .
    image: alantrrs/py-faster-rcnn
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - ./data/:/home/py-faster-rcnn/data
      - /tmp/.X11-unix:/tmp/.X11-unix
  demo-gpu:
    command: python tools/demo.py --net zf
    extends:
      service: demo
    devices:
      - /dev/nvidia0
      - /dev/nvidiactl
      - /dev/nvidia-uvm
  circle:
    command: python tools/demo.py --cpu --net zf
    extends:
      service: demo
    volumes:
      - $CIRCLE_ARTIFACTS:/tmp
  dev:
    image: alantrrs/py-faster-rcnn
    volumes:
      - .:/home/py-faster-rcnn
