version: '2'
services:
  demo:
    build: .
    image: alantrrs/py-faster-rcnn
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./data/:/home/py-faster-rcnn/data
    devices:
      - /dev/nvidia0
      - /dev/nvidiactl
      - /dev/nvidia-uvm
  dev:
    image: alantrrs/py-faster-rcnn
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/home/py-faster-rcnn

