version: '2'
services:
  demo:
    build: .
    image: alantrrs/py-faster-rcnn
    volumes:
      - ./data/:/home/py-faster-rcnn/data
    devices:
      - /dev/nvidia0
      - /dev/nvidiactl
      - /dev/nvidia-uvm
  dev:
    image: alantrrs/py-faster-rcnn
    volumes:
      - .:/home/py-faster-rcnn

